[Reward_2x2]
_model_ = "./models/modular_2x2_reward_implementation.modest"
_output_ = "./results/2x2.csv"
_type_ = "reward"
CLK_UPPER = "1:1:12"

[Modular_Fixed]
_model_ = "./models/modular2x2error.modest"
_output_ = "./tmp1.csv"
CLK_UPPER = "1:1:12"

[Modular_Reward]
_model_ = "./models/modular2x2-reward.modest"
_output_ = "./tmp2.csv"
CLK_UPPER = "12:1:12"